[nat]
brama ansible_host=i-048a211a22223c27c

[ad]
samba_dc ansible_host=i-01f99252a169d6c77

[all:vars]
ansible_aws_ssm_bucket_name=ssm-ansible-payloads-59693861ae055879af64c17cbd
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=eu-central-1
