[nat]
brama ansible_host=i-0abc60559c7f98367 ansible_user=ubuntu

[ad]
samba_dc ansible_host=i-02eacd545252c4e46 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p" -o StrictHostKeyChecking=no'
