[nat]
brama ansible_host=i-034d4082768b496de ansible_user=ubuntu

[ad]
samba_dc ansible_host=i-0ce07cf11da77cd44 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p" -o StrictHostKeyChecking=no'
