---
- name: Instalacja i konfiguracja Samba4 AD DC
  hosts: ad
  become: yes
  vars:
    domain_realm: "ls.ege.ds"
    domain_netbios: "LS"
    admin_pass: "P@ssw0rd2026!"

  tasks:
    - name: Aktualizacja apt i instalacja wymaganych pakietow
      apt:
        name:
          - samba
          - smbclient
          - winbind
          - libnss-winbind
          - krb5-user
          - krb5-config
        state: present
        update_cache: yes

    - name: Usuniecie domyslnego pliku smb.conf (aby AD moglo wygenerowac wlasny)
      file:
        path: /etc/samba/smb.conf
        state: absent

    - name: Provisionowanie (Tworzenie) nowej domeny Active Directory
      shell: >
        samba-tool domain provision 
        --server-role=dc 
        --use-rfc2307 
        --dns-backend=SAMBA_INTERNAL 
        --realm={{ domain_realm | upper }} 
        --domain={{ domain_netbios }} 
        --adminpass='{{ admin_pass }}'
      args:
        creates: /etc/samba/smb.conf

    - name: Wylaczenie standardowych uslug Samba (konfliktuja z wersja AD DC)
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        masked: yes
      loop:
        - smbd
        - nmbd
        - winbind

    - name: Uruchomienie zintegrowanej uslugi Samba AD DC
      systemd:
        name: samba-ad-dc
        state: started
        enabled: yes
        masked: no